<?php

/**
 * @file etonenet_sms.module
 */

/**
 * Implements hook_gateway_info().
 */
function etonenet_sms_gateway_info() {
  return array(
    'etonenet_sms' => array(
      'name' => 'Etonenet SMS Gateway',
      'send' => 'etonenet_sms_send',
      'receive' => FALSE,
      'configure form' => 'etonenet_sms_provider_setting_form',
    ),
  );
}

/**
 * Send SMS using etonenet service
 *
 * @param $number
 * @param $message
 * @param array $options
 *
 * @return String
 */
function etonenet_sms_send($number, $message, $options = array()) {
  $settings = variable_get('sms_etonenet_sms_settings');
  $etonenet_sms = new EtonenetSMS($settings['sms_provider_spid_name'], $settings['sms_provider_spid_pass'], $settings['sms_provider_service_url']);
  return $etonenet_sms->sendMessage($number, $message);
}

/**
 * Etonenet SMS settings form
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function etonenet_sms_provider_setting_form($configuration) {
  $form = array();

  // Add a new global question.
  $form['setting'] = array('#type' => 'container');

  $form['setting']['sms_provider_service_url'] = array(
    '#title' => t('SP Service Url'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('The service url of Etonenet SMS provider'),
    '#default_value' => isset($configuration['sms_provider_service_url']) ? $configuration['sms_provider_service_url'] : '',
  );

  $form['setting']['sms_provider_spid_name'] = array(
    '#title' => t('SPID'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Enter the SPID name.'),
    '#default_value' => isset($configuration['sms_provider_spid_name']) ? $configuration['sms_provider_spid_name'] : '',
  );

  $form['setting']['sms_provider_spid_pass'] = array(
    '#title' => t('SPID Password'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#description' => t('Enter the SPID password.'),
    '#default_value' => isset($configuration['sms_provider_spid_pass']) ? $configuration['sms_provider_spid_pass'] : '',
  );

  return $form;
}
